import { ToolCategory, ToolConfig } from '@/types/tools';

export const TOOL_CATEGORIES: ToolCategory[] = [
  'Career Tools',
  'Image Tools',
  'SEO Tools',
  'Marketing Tools',
  'Developer Tools',
  'Productivity Tools',
  'PDF Tools',
];

export const TOOLS_CONFIG: ToolConfig[] = [
  {
    slug: 'ai-image-metadata-remover',
    name: 'AI Image Metadata Remover',
    shortDescription: 'Scan and clean supported EXIF, GPS, XMP, IPTC, and C2PA metadata from images.',
    category: 'Image Tools',
    iconName: 'Sparkles',
    route: '/tools/ai-image-metadata-remover',
    status: 'active',
    badge: '100% Free',
    seoTitle: 'AI Image Metadata Remover - Remove EXIF, GPS & XMP | Skillsha',
    seoDescription: 'Free online image metadata remover by Skillsha. Scan and clean supported EXIF, GPS, XMP, IPTC and C2PA metadata from images.',
    keywords: [
      'image metadata remover',
      'remove exif data',
      'remove gps from photo',
      'strip xmp metadata',
      'c2pa metadata removal',
      'ai prompt remover',
    ],
  },
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    shortDescription: 'Compress JPEG, PNG, and WebP images with optimal quality-to-size balance.',
    category: 'Image Tools',
    iconName: 'Image',
    route: '/tools/image-compressor',
    status: 'active',
    badge: 'Popular',
    seoTitle: 'Free Online Image Compressor - Reduce Image Size | Skillsha',
    seoDescription: 'Compress JPEG, PNG, and WebP images online without losing quality. Fast browser compression, 100% free and private.',
    keywords: ['image compressor', 'compress png', 'compress jpg', 'reduce photo size', 'compress webp', 'online image optimizer'],
  },
  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    shortDescription: 'Resize images to custom pixel dimensions, percentage scale, or social media presets.',
    category: 'Image Tools',
    iconName: 'Maximize2',
    route: '/tools/image-resizer',
    status: 'active',
    badge: 'Popular',
    seoTitle: 'Free Online Image Resizer - Resize Photo Dimensions & Social Presets | Skillsha',
    seoDescription: 'Resize images online for free. Custom pixel dimensions, percentage scaling, aspect ratio lock, and ready presets for Instagram, YouTube, and LinkedIn.',
    keywords: [
      'image resizer',
      'resize photo online',
      'crop image for social media',
      'resize image in kb',
      'instagram photo resizer',
      'youtube thumbnail resizer',
      'free photo dimensions editor',
    ],
  },
  {
    slug: 'qr-generator',
    name: 'QR Code Generator',
    shortDescription: 'Create custom QR codes for URLs, Wi-Fi passwords, contacts, and marketing campaigns.',
    category: 'Marketing Tools',
    iconName: 'QrCode',
    route: '/tools/qr-generator',
    status: 'active',
    badge: 'Popular',
    seoTitle: 'Free QR Code Generator - Custom Colors, Logos, Wi-Fi & vCard | Skillsha',
    seoDescription: 'Generate high-resolution custom QR codes for your marketing and business needs. Download PNG and SVG.',
    keywords: ['qr code generator', 'free qr maker', 'wifi qr code', 'vcard qr code'],
  },
  {
    slug: 'utm-builder',
    name: 'UTM Campaign Builder',
    shortDescription: 'Build tracking URLs with standard Google Analytics UTM parameters and presets.',
    category: 'Marketing Tools',
    iconName: 'Link2',
    route: '/tools/utm-builder',
    status: 'active',
    badge: '100% Free',
    seoTitle: 'Free UTM Campaign Link Builder - Google Analytics 4 Generator | Skillsha',
    seoDescription: 'Generate properly formatted UTM tracking links for marketing campaigns, ad tracking, and email blasts.',
    keywords: ['utm builder', 'campaign url builder', 'google analytics utm link', 'ga4 utm generator'],
  },
  {
    slug: 'seo-meta-generator',
    name: 'SEO Meta Tag Generator',
    shortDescription: 'Generate OpenGraph, Twitter Cards, and canonical meta tags with live SERP preview.',
    category: 'SEO Tools',
    iconName: 'Globe',
    route: '/tools/seo-meta-generator',
    status: 'active',
    badge: 'Interactive',
    seoTitle: 'Free SEO Meta Tag Generator - HTML & Next.js Metadata | Skillsha',
    seoDescription: 'Create accurate SEO title tags, meta descriptions, and OpenGraph tags with live Google SERP previews.',
    keywords: ['seo meta tag generator', 'opengraph tags generator', 'twitter card maker', 'nextjs metadata generator'],
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    shortDescription: 'Format, validate, beautify, and minify complex JSON structures with syntax check.',
    category: 'Developer Tools',
    iconName: 'Code',
    route: '/tools/json-formatter',
    status: 'active',
    badge: 'Fast',
    seoTitle: 'Free JSON Formatter & Validator - Beautify, Minify & Auto-Repair | Skillsha',
    seoDescription: 'Clean and validate JSON data instantly with syntax highlighting, auto-repair, and tree visualization.',
    keywords: ['json formatter', 'json beautifier', 'json validator', 'repair json online'],
  },
  {
    slug: 'pdf-compressor',
    name: 'PDF Compressor',
    shortDescription: 'Reduce PDF document file size while preserving high visual quality and typography.',
    category: 'PDF Tools',
    iconName: 'FileText',
    route: '/tools/pdf-compressor',
    status: 'active',
    badge: 'Popular',
    seoTitle: 'Free PDF Compressor - Reduce PDF Size Online | Skillsha',
    seoDescription: 'Compress PDF files online securely and quickly without losing quality. 100% in-browser privacy.',
    keywords: ['pdf compressor', 'reduce pdf size', 'compress pdf online', 'pdf shrinker'],
  },
  {
    slug: 'ai-interview-preparation',
    name: 'AI Interview Preparation',
    shortDescription: 'Practice realistic interviews with AI based on your role, experience and resume.',
    category: 'Career Tools',
    iconName: 'Bot',
    route: '/tools/ai-interview-preparation',
    status: 'active',
    badge: 'AI Powered',
    ctaText: 'Start Practicing →',
    tags: ['HR', 'Technical', 'BPO', 'IT', 'Marketing'],
    seoTitle: 'AI Interview Preparation - Practice Mock Interviews with AI | Skillsha',
    seoDescription: 'Practice realistic AI-powered mock interviews tailored to your role, experience, and industry. Voice and text modes, STAR feedback, and personalized 7-day plan.',
    keywords: [
      'ai interview preparation',
      'ai mock interview',
      'interview practice online',
      'technical interview practice',
      'hr interview questions ai',
      'bpo mock interview',
      'star method interview',
    ],
  },
  {
    slug: 'ai-resume-builder',
    name: 'AI Resume Builder',
    shortDescription: 'Create a clean, ATS-compliant professional resume with live preview and instant export.',
    category: 'Career Tools',
    iconName: 'FileText',
    route: '/tools/ai-resume-builder',
    status: 'active',
    badge: 'Popular',
    ctaText: 'Build Resume →',
    tags: ['ATS Friendly', 'PDF Export', 'Live Preview', 'Free Templates'],
    seoTitle: 'Free AI Resume Builder - ATS Friendly Resume Maker | Skillsha',
    seoDescription: 'Build professional, ATS-compliant resumes online for free. Clean layouts, auto-enhanced bullet points, live preview, and instant PDF/Print download.',
    keywords: ['ai resume builder', 'ats resume maker', 'free online cv maker', 'resume generator', 'ats friendly cv template'],
  },
  {
    slug: 'ats-resume-checker',
    name: 'ATS Resume Checker',
    shortDescription: 'Scan your resume for ATS parseability, keyword match, action verbs, and impact score.',
    category: 'Career Tools',
    iconName: 'Search',
    route: '/tools/ats-resume-checker',
    status: 'active',
    badge: 'High Impact',
    ctaText: 'Check Resume →',
    tags: ['ATS Score', 'Keyword Audit', 'Action Verbs', 'Instant Scan'],
    seoTitle: 'Free ATS Resume Checker - Calculate Resume Score & Fix Errors | Skillsha',
    seoDescription: 'Check your resume ATS compatibility score (0-100) instantly. Scan for missing keywords, weak action verbs, formatting errors, and recruiter guidelines.',
    keywords: ['ats resume checker', 'resume score calculator', 'free ats scan', 'check cv for ats', 'ats scanner online'],
  },
  {
    slug: 'ai-cover-letter-generator',
    name: 'AI Cover Letter Generator',
    shortDescription: 'Generate tailored, high-converting cover letters matching your target role and company.',
    category: 'Career Tools',
    iconName: 'Mail',
    route: '/tools/ai-cover-letter-generator',
    status: 'active',
    badge: 'Fast',
    ctaText: 'Generate Letter →',
    tags: ['Job Specific', '3 Styles', 'Copy & Download', 'Recruiter Ready'],
    seoTitle: 'Free AI Cover Letter Generator - Role & Company Specific | Skillsha',
    seoDescription: 'Generate customized, professional cover letters in seconds. Tailored to your job description and resume with professional, results-driven, and modern styles.',
    keywords: ['ai cover letter generator', 'job application cover letter', 'free cover letter maker', 'tailored cover letter ai'],
  },
  {
    slug: 'job-description-analyzer',
    name: 'Job Description Analyzer',
    shortDescription: 'Extract core technical skills, soft skills, seniority clues, and salary expectations from any JD.',
    category: 'Career Tools',
    iconName: 'Target',
    route: '/tools/job-description-analyzer',
    status: 'active',
    badge: 'Essential',
    ctaText: 'Analyze JD →',
    tags: ['Skill Extraction', 'Salary Clues', 'Seniority Check', 'Resume Keywords'],
    seoTitle: 'Free Job Description Analyzer - Extract Skills & Keywords | Skillsha',
    seoDescription: 'Paste any job posting to extract must-have technical skills, soft skills, hidden requirements, seniority clues, and high-impact keywords for your resume.',
    keywords: ['job description analyzer', 'jd keyword extractor', 'extract skills from jd', 'job posting decoder'],
  },
  {
    slug: 'resume-vs-jd-matcher',
    name: 'Resume vs JD Matcher',
    shortDescription: 'Calculate the exact percentage match between your resume and a target job description.',
    category: 'Career Tools',
    iconName: 'Puzzle',
    route: '/tools/resume-vs-jd-matcher',
    status: 'active',
    badge: 'Top Pick',
    ctaText: 'Match Now →',
    tags: ['Match %', 'Missing Skills', 'Keyword Gap', 'Optimization'],
    seoTitle: 'Resume vs Job Description Matcher - Free Keyword Gap Tool | Skillsha',
    seoDescription: 'Compare your resume against any job description to discover your match percentage, identified skills, and missing critical keywords needed to pass recruiter filters.',
    keywords: ['resume vs jd matcher', 'resume job match percentage', 'match cv with job description', 'ats keyword gap'],
  },
  {
    slug: 'career-path-finder',
    name: 'Career Path Finder',
    shortDescription: 'Discover the best career trajectories and bridge skills based on your current background.',
    category: 'Career Tools',
    iconName: 'Compass',
    route: '/tools/career-path-finder',
    status: 'active',
    badge: 'Strategic',
    ctaText: 'Find Path →',
    tags: ['Career Growth', 'Bridge Skills', 'Transition Score', 'Role Hierarchy'],
    seoTitle: 'Free Career Path Finder - Map Your Career Trajectory & Roles | Skillsha',
    seoDescription: 'Identify the top 3 high-growth career paths for your current skillset. Compare transition difficulty, salary growth potential, and required bridge competencies.',
    keywords: ['career path finder', 'career trajectory planner', 'switch careers roadmap', 'future job roles finder'],
  },
  {
    slug: 'salary-estimator',
    name: 'Salary Estimator',
    shortDescription: 'Estimate realistic market CTC & in-hand salary ranges by role, experience, and city.',
    category: 'Career Tools',
    iconName: 'DollarSign',
    route: '/tools/salary-estimator',
    status: 'active',
    badge: 'Accurate',
    ctaText: 'Estimate Salary →',
    tags: ['Market CTC', 'In-Hand Pay', 'City Benchmarks', 'Salary Multipliers'],
    seoTitle: 'Free Salary Estimator India - Role, Experience & City Pay Benchmarks | Skillsha',
    seoDescription: 'Calculate realistic Indian tech and corporate salary ranges (LPA & monthly in-hand). Benchmark your compensation by experience, city, and high-demand skills.',
    keywords: ['salary estimator india', 'tech salary calculator', 'fresher salary benchmark', 'software engineer salary range india'],
  },
  {
    slug: 'skill-gap-analyzer',
    name: 'Skill Gap Analyzer',
    shortDescription: 'Compare your skills against your dream job to isolate high-priority gaps and 2-week quick wins.',
    category: 'Career Tools',
    iconName: 'TrendingUp',
    route: '/tools/skill-gap-analyzer',
    status: 'active',
    badge: 'Targeted',
    ctaText: 'Analyze Gaps →',
    tags: ['Must Have Skills', 'Quick Wins', 'Job Readiness', 'Upskilling Priority'],
    seoTitle: 'Free Skill Gap Analyzer - Identify Missing Skills for Target Jobs | Skillsha',
    seoDescription: 'Isolate exactly what skills you lack for your target job. Get an actionable priority breakdown categorized by Must-Have, Good-to-Have, and 2-week quick wins.',
    keywords: ['skill gap analyzer', 'skills assessment for job', 'missing skills identifier', 'upskilling roadmap'],
  },
  {
    slug: 'career-roadmap-generator',
    name: 'Career Roadmap Generator',
    shortDescription: 'Create a structured 3, 6, or 12-month step-by-step learning and portfolio roadmap.',
    category: 'Career Tools',
    iconName: 'MapPin',
    route: '/tools/career-roadmap-generator',
    status: 'active',
    badge: 'Structured',
    ctaText: 'Generate Roadmap →',
    tags: ['3/6/12 Months', 'Monthly Goals', 'Portfolio Projects', 'Study Plan'],
    seoTitle: 'Free Career Roadmap Generator - 3, 6 & 12 Month Study Plans | Skillsha',
    seoDescription: 'Generate structured learning roadmaps for IT, Data, Marketing, and Management roles. Includes weekly topics, portfolio project milestones, and progress tracking.',
    keywords: ['career roadmap generator', 'learning roadmap maker', 'software developer roadmap generator', 'study plan maker'],
  },
  {
    slug: 'linkedin-profile-optimizer',
    name: 'LinkedIn Profile Optimizer',
    shortDescription: 'Craft recruiter-optimized headlines, compelling storytelling About bios, and keyword tags.',
    category: 'Career Tools',
    iconName: 'Share2',
    route: '/tools/linkedin-profile-optimizer',
    status: 'active',
    badge: 'Visibility',
    ctaText: 'Optimize Profile →',
    tags: ['High-CTR Headline', 'About Bio Story', 'Top 5 Skills', 'Recruiter SEO'],
    seoTitle: 'Free LinkedIn Profile Optimizer - Headlines, About Section & SEO | Skillsha',
    seoDescription: 'Generate high-CTR LinkedIn headlines, storytelling About summaries, and recruiter search keywords. Stand out in LinkedIn Recruiter searches and land more interviews.',
    keywords: ['linkedin profile optimizer', 'linkedin headline generator', 'linkedin summary generator', 'linkedin recruiter seo'],
  },
  {
    slug: 'job-application-email-generator',
    name: 'Job Application Email Generator',
    shortDescription: 'Write professional, high-reply-rate emails for HR applications, referrals, and follow-ups.',
    category: 'Career Tools',
    iconName: 'Send',
    route: '/tools/job-application-email-generator',
    status: 'active',
    badge: 'High Reply',
    ctaText: 'Write Email →',
    tags: ['Cold Outreach', 'Referral Request', 'Follow-up Email', 'HR Direct Application'],
    seoTitle: 'Free Job Application Email Generator - HR, Referrals & Follow-ups | Skillsha',
    seoDescription: 'Generate high-open-rate job application emails, employee referral requests, cold outreach messages, and interview follow-up templates in one click.',
    keywords: ['job application email generator', 'email to hr for job application', 'referral request email template', 'interview follow up email'],
  },
];

export function getToolBySlug(slug: string): ToolConfig | undefined {
  return TOOLS_CONFIG.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): ToolConfig[] {
  return TOOLS_CONFIG.filter((tool) => tool.category === category);
}

export function getActiveTools(): ToolConfig[] {
  return TOOLS_CONFIG.filter((tool) => tool.status === 'active');
}
