import { ToolCategory, ToolConfig } from '@/types/tools';

export const TOOL_CATEGORIES: ToolCategory[] = [
  'Image Tools',
  'SEO Tools',
  'Marketing Tools',
  'Developer Tools',
  'Productivity Tools',
  'PDF Tools',
];

export const TOOLS_CONFIG: ToolConfig[] = [
  {
    slug: 'ai-image-metadata-remover',
    name: 'AI Image Metadata Remover',
    shortDescription: 'Scan and clean supported EXIF, GPS, XMP, IPTC, and C2PA metadata from images.',
    category: 'Image Tools',
    iconName: 'Sparkles',
    route: '/tools/ai-image-metadata-remover',
    status: 'active',
    badge: '100% Free',
    seoTitle: 'AI Image Metadata Remover - Remove EXIF, GPS & XMP | Skillsha',
    seoDescription: 'Free online image metadata remover by Skillsha. Scan and clean supported EXIF, GPS, XMP, IPTC and C2PA metadata from images.',
    keywords: [
      'image metadata remover',
      'remove exif data',
      'remove gps from photo',
      'strip xmp metadata',
      'c2pa metadata removal',
      'ai prompt remover',
    ],
  },
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    shortDescription: 'Compress JPEG, PNG, and WebP images with optimal quality-to-size balance.',
    category: 'Image Tools',
    iconName: 'Image',
    route: '/tools/image-compressor',
    status: 'active',
    badge: 'Popular',
    seoTitle: 'Free Online Image Compressor - Reduce Image Size | Skillsha',
    seoDescription: 'Compress JPEG, PNG, and WebP images online without losing quality. Fast browser compression, 100% free and private.',
    keywords: ['image compressor', 'compress png', 'compress jpg', 'reduce photo size', 'compress webp', 'online image optimizer'],
  },
  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    shortDescription: 'Resize images to custom pixel dimensions, percentage scale, or social media presets.',
    category: 'Image Tools',
    iconName: 'Maximize2',
    route: '/tools/image-resizer',
    status: 'active',
    badge: 'Popular',
    seoTitle: 'Free Online Image Resizer - Resize Photo Dimensions & Social Presets | Skillsha',
    seoDescription: 'Resize images online for free. Custom pixel dimensions, percentage scaling, aspect ratio lock, and ready presets for Instagram, YouTube, and LinkedIn.',
    keywords: [
      'image resizer',
      'resize photo online',
      'crop image for social media',
      'resize image in kb',
      'instagram photo resizer',
      'youtube thumbnail resizer',
      'free photo dimensions editor',
    ],
  },
  {
    slug: 'qr-generator',
    name: 'QR Code Generator',
    shortDescription: 'Create custom QR codes for URLs, Wi-Fi passwords, contacts, and marketing campaigns.',
    category: 'Marketing Tools',
    iconName: 'QrCode',
    route: '/tools/qr-generator',
    status: 'active',
    badge: 'Popular',
    seoTitle: 'Free QR Code Generator - Custom Colors, Logos, Wi-Fi & vCard | Skillsha',
    seoDescription: 'Generate high-resolution custom QR codes for your marketing and business needs. Download PNG and SVG.',
    keywords: ['qr code generator', 'free qr maker', 'wifi qr code', 'vcard qr code'],
  },
  {
    slug: 'utm-builder',
    name: 'UTM Campaign Builder',
    shortDescription: 'Build tracking URLs with standard Google Analytics UTM parameters and presets.',
    category: 'Marketing Tools',
    iconName: 'Link2',
    route: '/tools/utm-builder',
    status: 'active',
    badge: '100% Free',
    seoTitle: 'Free UTM Campaign Link Builder - Google Analytics 4 Generator | Skillsha',
    seoDescription: 'Generate properly formatted UTM tracking links for marketing campaigns, ad tracking, and email blasts.',
    keywords: ['utm builder', 'campaign url builder', 'google analytics utm link', 'ga4 utm generator'],
  },
  {
    slug: 'seo-meta-generator',
    name: 'SEO Meta Tag Generator',
    shortDescription: 'Generate OpenGraph, Twitter Cards, and canonical meta tags with live SERP preview.',
    category: 'SEO Tools',
    iconName: 'Globe',
    route: '/tools/seo-meta-generator',
    status: 'active',
    badge: 'Interactive',
    seoTitle: 'Free SEO Meta Tag Generator - HTML & Next.js Metadata | Skillsha',
    seoDescription: 'Create accurate SEO title tags, meta descriptions, and OpenGraph tags with live Google SERP previews.',
    keywords: ['seo meta tag generator', 'opengraph tags generator', 'twitter card maker', 'nextjs metadata generator'],
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    shortDescription: 'Format, validate, beautify, and minify complex JSON structures with syntax check.',
    category: 'Developer Tools',
    iconName: 'Code',
    route: '/tools/json-formatter',
    status: 'active',
    badge: 'Fast',
    seoTitle: 'Free JSON Formatter & Validator - Beautify, Minify & Auto-Repair | Skillsha',
    seoDescription: 'Clean and validate JSON data instantly with syntax highlighting, auto-repair, and tree visualization.',
    keywords: ['json formatter', 'json beautifier', 'json validator', 'repair json online'],
  },
  {
    slug: 'pdf-compressor',
    name: 'PDF Compressor',
    shortDescription: 'Reduce PDF document file size while preserving high visual quality and typography.',
    category: 'PDF Tools',
    iconName: 'FileText',
    route: '/tools/pdf-compressor',
    status: 'active',
    badge: 'Popular',
    seoTitle: 'Free PDF Compressor - Reduce PDF Size Online | Skillsha',
    seoDescription: 'Compress PDF files online securely and quickly without losing quality. 100% in-browser privacy.',
    keywords: ['pdf compressor', 'reduce pdf size', 'compress pdf online', 'pdf shrinker'],
  },
  {
    slug: 'ai-interview-preparation',
    name: 'AI Interview Preparation',
    shortDescription: 'Practice realistic AI-powered interviews tailored to your role, experience and industry.',
    category: 'Productivity Tools',
    iconName: 'Bot',
    route: '/tools/ai-interview-preparation',
    status: 'active',
    badge: 'AI Powered',
    ctaText: 'Start Interview',
    secondaryText: 'Practice HR, Technical, BPO, IT, Digital Marketing, Sales and more.',
    seoTitle: 'AI Interview Preparation - Practice Mock Interviews with AI | Skillsha',
    seoDescription: 'Practice realistic AI-powered mock interviews tailored to your role, experience, and industry. Voice and text modes, STAR feedback, and personalized 7-day plan.',
    keywords: [
      'ai interview preparation',
      'ai mock interview',
      'interview practice online',
      'technical interview practice',
      'hr interview questions ai',
      'bpo mock interview',
      'star method interview',
    ],
  },
];

export function getToolBySlug(slug: string): ToolConfig | undefined {
  return TOOLS_CONFIG.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): ToolConfig[] {
  return TOOLS_CONFIG.filter((tool) => tool.category === category);
}

export function getActiveTools(): ToolConfig[] {
  return TOOLS_CONFIG.filter((tool) => tool.status === 'active');
}
